---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Include ansible-test-molecule-different-ansible-versions-and-distros"
      include_role:
        name: "ansible-test-molecule-different-ansible-versions-and-distros"
